### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by gshukov98** [Specter-13/blazorgenui#4]
Hi, 
How you release new nuget packages. If you do it manually do you want we to automate this for you?

Regards,
Elders

**Comment by Specter-13** [comment]
Yes, nuget are released manually.

**Comment by gshukov98** [comment]
Can you describe how exactly you do it?

And we can give you better solution for releasing if you want.

**Comment by Specter-13** [comment]
I did it manually within VisualStudio. It would be nice, if it was automated with CI/CD pipeline.

**Comment by gshukov98** [comment]
Ok, but to can configure this you should give me editor access to your repository.

**Comment by Specter-13** [comment]
I sent you an invitation.

**Comment by gshukov98** [comment]
Thank you, I will start working on this.
And when I have any progress I will inform you.

**Comment by gshukov98** [comment]
Can you add new secret from repo settings with name NUGET_AUTH_TOKEN and value your nuget gallery secret key

**Comment by gshukov98** [comment]
Hi, at the moment pipeline for BlazorGenUI.Components is ready
Just you need to add this secret from last comment, then I can test the pipe line and will add it and for the other project.
![image](https://user-images.githubusercontent.com/56069656/143556585-c1dc61df-0400-4052-ba2e-0f15e502498b.png)

**Comment by Specter-13** [comment]
Hey, will do ASAP, I will ping you.

**Comment by Specter-13** [comment]
@gshukov98 done.

**Comment by gshukov98** [comment]
Thank you!

**Comment by Specter-13** [comment]
Thank you for awesome work and interest in this project!
